version: "2"

services:

    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/postgres:latest
        networks:
            - hadoop
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "15432:5432"
        environment:
            POSTGRES_PASSWORD: postgres

volumes:
    postgres_data:

networks:
    hadoop:
        driver: bridge
