version: "3"

services:

    postgres:
        build:
            context: .
            dockerfile: Dockerfile        
        image: mcapitanio/postgres:9.6
        networks:
            - hadoop
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres

networks:
    hadoop:
        driver: bridge
