version: "3"

services:

    postgres:
        build:
            context: .
            dockerfile: Dockerfile        
        image: comchangs/postgres:latest
        networks:
            - parrot
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres

networks:
    default:
        external:
            name: comchangs
    parrot:
        driver: bridge
